spring.application.name=gatekeeperpattern
server.port=9000

spring.cloud.gateway.routes[0].id=api-route
spring.cloud.gateway.routes[0].uri=${API_URL:http://localhost:3333}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=front-route
spring.cloud.gateway.routes[1].uri=${WEB_URL:http://localhost:3000}
spring.cloud.gateway.routes[1].predicates[0]=Path=/**

jwt.secret=${JWT_SECRET:default_secret_key_change_in_production}

